repos:
  - repo: local
    hooks:
      - id: black
        name: ruff fix (uv)
        entry: uv run ruff check --fix .
        language: system
        pass_filenames: false
      - id: ruff-format
        name: ruff format (uv)
        entry: uv run ruff format .
        language: system
        pass_filenames: false
      - id: isort
        name: isort (uv)
        entry: uv run isort .
        language: system
        pass_filenames: false
      - id: mypy
        name: mypy (uv)
        entry: uv run mypy .
        language: system
        pass_filenames: false
      - id: deadcode
        name: deadcode (uv)
        entry: uv run deadcode llm_scanner
        language: system
        pass_filenames: false
      - id: pytest
        name: pytest (uv)
        entry: uv run pytest tests/
        language: system
        pass_filenames: false
